### ISSUE TITLE
"Treating 'lodash-es/escape' as external dependency"

### ISSUE THREAD

**Issue by SpaceK33z** [btd/rollup-plugin-jst#1]
Hi, when bundling with Rollup I'm getting this message: `Treating 'lodash-es/escape' as external dependency`. But I have installed lodash-es with `npm i -S lodash-es`, so it should use that one, right?

**Comment by btd** [comment]
Hi, nope.

By default `rollup` search only local dependencies (from cwd). To make it use npm dependencies you need to install also `rollup-node-resolve-plugin`, for example:

``` js
{
    entry: entry,
    sourceMap: sourceMap,
    format: 'iife',
    plugins: [
      rollupJst(),
      rollupNodeResolve({
        jsnext: true,
        main: true
      })
    ]
  }
```

So this plugin just convert template to some sort of javascript file, next rollup uses node resolve to search for dependencies among npm deps.

**Comment by SpaceK33z** [comment]
Ah okay, thanks for your explanation. I'm coming from webpack and assumed resolving was the same, sorry.

**Comment by btd** [comment]
No problem at all. Feel free to ask questions. I have added to readme node-resolve plugin to make it a bit more clear.
