### ISSUE TITLE
More detailed examples

### ISSUE THREAD

**Issue by Shyam-Chen** [btd/rollup-plugin-jst#2]

**Comment by btd** [comment]
Any directions what is not clear in readme?

**Comment by Shyam-Chen** [comment]
Do not only configure.

**Comment by btd** [comment]
Not sure it is required. Configuring it is single thing required. After configuration, if you import any template by extension rollup will trigger this module. That is simply all.
Just like:
```js
import tpl from './templates/header.html';

tpl({ a: 10 })
```

**Comment by Shyam-Chen** [comment]
Or can you help me add lodash template?

https://github.com/Vanilla-IceCream/rollup-plugin-posthtml-template

**Comment by btd** [comment]
This plugin will help you in that project. Rollup plugins always convert something to javascript code (module). So as your plugin as this one both convert html to js. That is why they could not be used togather by the same include filter. 
If you need templates, it is better just copy code from this repo, it is very simple.
