### ISSUE TITLE
Uncaught ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by boussou** [btd/rollup-plugin-jst#4]
I don't how you use it if you use it,
but each time you use a construct like `<% _.each(...`  you got this message.

I had to add the import llke this:

      ...
      const intro = hasEscape ? "import escape from " + JSON.stringify(escapeModule) + ";" : "";
      const intro2 = "import _ from  'lodash';" ;

      return `
      ${intro}
      ${intro2}
      export default ${source}
      `;

I there a better way?

**Comment by btd** [comment]
If i am not mistaken you can add `templateOptions` to plugin:
```js
jst({ 
  templateOptions: {
    variable: 'data',
    imports: { _ }
  }
});
